eduNEXT/eox-tenant

eox_tenant/backends/base.py

Addressing error encountered while running tests in the lms with the plugin installed in the venv

Fixes error while running tests

---

eox_tenant/admin.py

This PR makes it easy to see on the admin which sites have activated signals

Adding a new field to the admin page

---

eox_tenant/tenant_aware_functions/enrollments.py

This PR adds a filter_enrollments function to be used from edunext-platform, to filter the student enrollments according to the organization value.

FFI-3 - Add filter_enrollments function.

---

eox_tenant/settings/test.py
eox_tenant/signals.py
eox_tenant/test/test_signals.py

This PR fixes cms test running on Circle CI.

BC-19 Fix | Using SETTINGS_MODULE to find the cms

---

eox_tenant/backends/database.py

Moving custom microsite implementation over from core platform

BC-21 | Custom microsite methods

---

.circleci/config.yml
eox_tenant/edxapp_wrapper/backends/configuration_helpers_h_v1.py
eox_tenant/edxapp_wrapper/branding_api.py
eox_tenant/edxapp_wrapper/configuration_helpers.py
eox_tenant/settings/branding_api_h_v1.py
eox_tenant/settings/common.py
eox_tenant/templatetags/ednx.py
eox_tenant/test/test_wrappers.py
setup.cfg

This feature needs to have properly configured **CONTACT_EMAIL** and **LMS_ROOT_URL** for each microsite
Related to https://github.com/eduNEXT/edunext-platform/pull/244

Template-tags changes for ha/ednx/he

---

eox_tenant/templatetags/ednx.py

This PR makes microsite_get_value a tag

Registering a tag instead of a filter

---

eox_tenant/__init__.py
eox_tenant/apps.py

This branch allows to connect the request signals with the receiver functions defined on the signals.py file.

Connect signals

---

eox_tenant/admin.py

This PR adds a django admin interface to handle Route model.
@jfavellar90 
@Squirrel18

adding route model admin

---

eox_tenant/templatetags/ednx.py

Change to use configuration helpers instead of microsites

Use configuration helpers instead of microsites

---

eox_tenant/templatetags/ednx.py

Adding template tags and filter with more meaningful names, and adding deprecation notes for methods including the name "microsite"
@morenol 
@anmrdz 
@cocococosti

Template tags and filters for tenants

---

eox_tenant/management/commands/change_domain.py
eox_tenant/test/test_change_domain.py

Changing the change_domain command to affect the ecommerce urls as well
@morenol 
@cocococosti

Changing the change_domain command to affect the ecommerce urls as well

---

eox_tenant/auth.py

Running custom auth-on-tenant validation for all sites by removing non backwards compatible feature flag.
The auth-on-tenant validation is performed for all tenants and the EDNX_ENABLE_STRICT_LOGIN feature flag still keeps control on when to enforce the restricted login or just log when in fact a user should have been blocked on that login action.
@morenol 
@cocococosti

Fix non backwards compatible feature flag

---

eox_tenant/settings/aws.py
eox_tenant/settings/common.py

Making the append of the LMS middlewares optional
@cocococosti 
@morenol 
@felipemontoya

Making the append of the LMS middlewares optional

---

eox_tenant/backends/database.py

This method is already defined in ox_tenant.backends.base.BaseMicrositeBackend

Remove duplicated method

---

eox_tenant/apps.py
eox_tenant/signals.py
eox_tenant/test/test_signals.py

Connect studio signals and remove studio conditional.

Add support for studio.

---

eox_tenant/edxapp_wrapper/backends/certificates_module_i_v1.py
eox_tenant/settings/common.py
eox_tenant/signals.py
eox_tenant/tenant_wise/__init__.py
eox_tenant/test_utils.py

- Verify dependency fake_model
- turn off by default.

Fixing platform tests.

---

eox_tenant/organizations.py
eox_tenant/tenant_wise/__init__.py
eox_tenant/tenant_wise/proxies.py
eox_tenant/test/test_tenant_wise.py
eox_tenant/test_utils.py

Improve certificates get_queryset method performance, using Q objects.
Another option is the following code but this is three times slower
```
course_ids = CourseOverview.get_all_courses(orgs=org_filter).values_list("id", flat=True)
return generated_certificates.filter(course_id__in=course_ids)
```

Improve performance certificates.

---

eox_tenant/migrations/0005_auto_20191226_1225.py

This checks if the mysql version is mayor to 5.7 and allows to run the migrations.

Add condition for migrations.

---

eox_tenant/admin.py
eox_tenant/templates/eox-tenant/widgets/json_widget.html
eox_tenant/widgets.py

---------------
- now JSONFields can be indented using JsonWidget.

Add indent in admin JSONField

---

eox_tenant/tenant_wise/proxies.py

Return the full settings as a dict.

Return the settings as a dict in the property values.

---

eox_tenant/tenant_wise/proxies.py

Avoid to save the settings values

Fix pickle error.

---

eox_tenant/tenant_wise/__init__.py

This allows to use any proxy in a whole djangoapp.

Monkey patching by djangoapp.

---

eox_tenant/admin.py
eox_tenant/models.py

- Add a search in the admin for fields that are JSONField, for TenantConfig and Microsite models.
- Fix a 500 error that was generated when trying to search these views.

Search in JSONFields for listview in admin

---

.circleci/config.yml

Use cache for test in circleci.

Allow to use cache in circleci.

---

.circleci/config.yml

This PR adds a new job with python3.5

Add python 3.5

---

.circleci/config.yml

Use circleci matrix to run the tests.

Use circleci matrix

---

CHANGELOG.rst
eox_tenant/edxapp_wrapper/backends/users_test_v1.py
eox_tenant/management/commands/change_signup_sources.py
eox_tenant/settings/test.py
eox_tenant/test/test_change_signupsource.py
eox_tenant/test/test_utils.py
eox_tenant/utils.py
requirements.in
requirements.txt

Add a new command to move signup sources from one domain to another.
Before merge:

Add new command to change signup sources

---

CHANGELOG.rst
eox_tenant/tenant_wise/proxies.py

Use new `get_value_for_org` method, get organizations from its model and remove deprecated methods

Implement new get_value_for_org method

---

MANIFEST.in

Adding a manifest for the installation in non-editable mode

Adding a manifest for the installation in non-editable mode

---

MANIFEST.in
setup.py

Fix manifest and include packages

Include package data a fix manifest

---

eox_tenant/edxapp_wrapper/auth.py
eox_tenant/edxapp_wrapper/backends/edx_auth_i_v1.py
eox_tenant/validators.py

This PR adds a new file that contains a class, this class inherits from EdxOAuth2Validator.

Add a new validator for token usage

---

eox_tenant/edxapp_wrapper/auth.py
eox_tenant/edxapp_wrapper/backends/edx_auth_i_v1.py
eox_tenant/edxapp_wrapper/backends/oauth_dispatch_j_v1.py
eox_tenant/edxapp_wrapper/oauth_dispatch.py
eox_tenant/settings/common.py
eox_tenant/validators.py

This PR add a backend for the token validator.

Backend for token validator

---

eox_tenant/validators.py

This PR adds a method to save the token if the actual url is in redirect_uris list.

Add method save_bearer_token

---

eox_tenant/validators.py

This PR fix the save_bearer_method.

Fix save_bearer_token method

---

CHANGELOG.rst
eox_tenant/validators.py

feat: allow to create tokes if the application is in the list ALLOWED_AUTH_APPLICATIONS

Allow to create tokens for applications in list

---

CHANGELOG.rst
eox_tenant/edxapp_wrapper/backends/branding_api_l_v1.py
eox_tenant/edxapp_wrapper/backends/users_l_v1.py
eox_tenant/settings/common.py
eox_tenant/settings/production.py
eox_tenant/tenant_wise/__init__.py

This pr is the same that https://github.com/eduNEXT/eox-tenant/pull/124, but I closed it since I deleted the base branch.

feat!: Add lilac backends.

---

CHANGELOG.rst
eox_tenant/settings/common.py

Revert changes since the lms test fails

feat: Revert backends changes.

---

eox_tenant/__init__.py
setup.cfg

Bump version: 5.1.3 → 6.0.0

---

README.rst

Add caveats section describing the issue with middleware reported [here](https://github.com/eduNEXT/eox-tenant/issues/172).
Just docs update.
Check the issue mentioned above.

docs: add caveats section describing issue with middleware

---

commitlint.config.js

Cherry-pick from this PR
https://github.com/eduNEXT/eox-tenant/pull/193

feat: add openedx commitlint.config.js

---

CHANGELOG.md
eox_tenant/__init__.py
eox_tenant/constants.py
eox_tenant/validators.py
setup.cfg

A base allowed application list has been added to avoid issues with studio and aspects login

feat: added base allowed application
