eduNEXT/eox-tenant

eox_tenant/backends/database.py
eox_tenant/edxapp_wrapper/backends/microsite_configuration_test_v1.py
eox_tenant/models.py
eox_tenant/settings/aws.py
eox_tenant/settings/common.py
eox_tenant/settings/test.py
eox_tenant/signals.py
eox_tenant/test/test_signals.py
requirements.in
requirements.txt

This PR defines new functions to be called from the request_started django signal. This will modify the django.conf.settings object for the duration of the python process
Note to reviewers: please go through this soon and be ruthless
TODO
--------
FYI
-----
@jfavellar90 @morenol @Alec4r @andrey-canon

Adding signals as new tenancy model

---

eox_tenant/signals.py

Fixes the case where a given key exists as a string on the base_settings and a dict on the tenant

Edge case on dicts initialized on top of strings

---

eox_tenant/settings/test.py

Simple. When we run the tests from the edxapp virtualenv and this is installed, we don't want the redirection middleware being activated because it changes the numbers of queries and a lot of tests break

Disabling custom middleware for testing on the platform

---

.circleci/config.yml
Makefile
eox_tenant/test/test_change_domain.py

This PR adds test file to change_domain command and also updates the coverage report score to 40.
FYI: 
I forget to add this test file in the [Add eox middlewares PR](https://github.com/eduNEXT/eox-tenant/pull/12).
@diegomillan

BC21 - Add test to change_domain command.

---

eox_tenant/settings/test.py
eox_tenant/signals.py
eox_tenant/test/test_signals.py

This PR goes back to use SERVICE_VARIANT to check if the request comes from either, cms or lms.

HA/EDNX/BC-19 - Using service variant to find cms.

---

eox_tenant/settings/test.py
eox_tenant/tenant_aware_functions/enrollments.py

This PR adds an if statement to filter_enrollments function to verify if the function was called during the test process.
This is because some certificates test are failing due to the filter_enrollments function makes more database calls than normal behaviour.

HA/EDNX/FFI-3 - Add if statement to fix lms tests.

---

eox_tenant/migrations/0001_initial.py
eox_tenant/models.py

This PR solves the error raised when we used this on a db that was copied from production. The table name had an incorrect name.
For local environments, a new `./load-db edxapp` command must be issued

Correcting the database name to match prod db

---

.circleci/config.yml
eox_tenant/management/commands/change_domain.py
eox_tenant/management/commands/edit_tenant_values.py
eox_tenant/test/test_change_domain.py
eox_tenant/test/test_edit_tenant_values.py

This PR adds a new edit_tenant_values django command.
The command supports adding and removing nested keys and using basic interpolation with the tenant values. Also supports pattern filtering to select the sites it will operate on.

Adding command to modify tenants over a cli.

---

eox_tenant/backends/database.py

During stage testing, when we try to go to unknow microsite url, the RedirectionsMiddleware does not redirect to the 404 page. This patch removes the is_request_in_microsite since the right implementation is already in the base.py backend, and adds a reading of USE_MICROSITES settings in has_configuration_set().

HA/EDNX/HA-23 - Fix site not found middleware error.

---

.circleci/config.yml
eox_tenant/signals.py
eox_tenant/test/test_signals.py

This PR allows a particular tenant to reload the AppConfig from a INSTALLED_APP after the settings are reset.
This  fixes the issue we had on the ThirdPartyAuth sad paths.
The method called here: https://github.com/eduNEXT/edunext-platform/blob/master/common/djangoapps/third_party_auth/apps.py#L15 overrides some settings that where reset on the signal call.
We allow a tenant to decide if it wants any app being reloaded again using `EDNX_TENANT_INSTALLED_APPS`

Reloading apps as configured in the tenant

---

eox_tenant/management/commands/change_domain.py
eox_tenant/settings/test.py
eox_tenant/test/test_change_domain.py

This PR allows to control in a better way how the stage domains are build. Specifically in the case where the provided suffix domains starts with a dot, for example ".i.stage.edunext.co". In this case we don't need a hyphen (-) as separator of the transformed microsite domain and the suffix.
@morenol 
@cocococosti 
@felipemontoya

Improving a bit the change_domain command

---

.circleci/config.yml
Makefile
eox_tenant/edxapp_wrapper/backends/microsite_configuration_test_v1.py

Fixing tests by moving import. For some reason, the tests were failing randomly. According to my investigation we apparently inserted this problem in HA-3 (https://circleci.com/gh/eduNEXT/eox-tenant/602) and from that moment we get the tests failure sometimes in python 2.7. I ran the tests with this fix 4 consecutive times with no failures. Strange thing here: I was no able to replicate the problem running the tests in dev.
**Reason of the change**
From the traceback you can check in https://circleci.com/gh/eduNEXT/eox-tenant/602 there were nested calls of **import_module** method and that was causing a strange behavior
I also changed the Makefile to use the same fail-under value for local coverage tests
@morenol 
@anmrdz 
@cocococosti

Fixing tests by moving import.

---

eox_tenant/auth.py
eox_tenant/edxapp_wrapper/auth.py
eox_tenant/edxapp_wrapper/backends/edx_auth_i_v1.py
eox_tenant/settings/aws.py
eox_tenant/settings/common.py
eox_tenant/test/test_auth_backend.py

This PR adds an AuthenticationBackend that prevents users that signed up on a tenant site to login in other sites.
It also adds the capability to restrict the login in a tenant site to the users with an email that matches with the REGISTRATION_EMAIL_PATTERNS_ALLOWED pattern
This changes are based on:
https://github.com/eduNEXT/edunext-platform/commits/a52131f0a631398649eeb8241e89743feb18136f/common/djangoapps/student/views

[WIP] Ir/ednx/ir 20

---

eox_tenant/management/commands/change_domain.py
eox_tenant/test/test_change_domain.py

When the site name is something like: example.com:18000,
The method change_subdomain is returning  example-com:18000-stage.edunext.co instead of 
example-com-stage.edunext.co:18000 or example-com-stage.edunext.co

Handle site names with the format hostname:port

---

eox_tenant/auth.py
eox_tenant/test/test_auth_backend.py

This backend should ignore case. Otherwise we would not be able to authenticate in
example.com if we have a signupsource.site like 'Example.com'

Ignore case in signup source authenticaticon backend

---

eox_tenant/settings/test.py
eox_tenant/tenant_aware_functions/enrollments.py
eox_tenant/test/test_tenant_aware_functions.py

Try-catching the custom permissions loading if the django tables don't exist yet. This will fix the edxapp tests run
@morenol 
@cocococosti

Changes to fix edxapp tests

---

eox_tenant/settings/aws.py

Adding CMS microsite middleware in a specific position to prevent failure on the studio language selector. This is a quite dirty fix but this middleware will disappear in the Juniper release.
@cocococosti 
@morenol

Adding CMS microsite middleware in a specific position

---

eox_tenant/pipeline.py
eox_tenant/test/test_pipeline.py

This PR adds a function that does the same as https://github.com/python-social-auth/social-core/blob/master/social_core/pipeline/social_auth.py#L51, but protects admin users

Adding a pipeline function to associate users excluding admins

---

.circleci/config.yml
Makefile
eox_tenant/apps.py
eox_tenant/async_utils.py
eox_tenant/settings/aws.py
eox_tenant/settings/common.py
eox_tenant/settings/test.py
eox_tenant/signals.py
eox_tenant/test/test_async_utils.py
eox_tenant/test/test_signals.py

Handle celery signals (celery.signals.before_task_publish and celery.signals.task_prerun) to change the settings of the async process accordingly to the tenant configurations.

tenancy for async tasks

---

eox_tenant/edxapp_wrapper/backends/certificates_module_i_v1.py
eox_tenant/edxapp_wrapper/backends/certificates_module_test_v1.py
eox_tenant/edxapp_wrapper/certificates_module.py
eox_tenant/settings/aws.py
eox_tenant/settings/common.py
eox_tenant/settings/test.py
eox_tenant/tenant_wise/__init__.py
eox_tenant/tenant_wise/proxies.py
eox_tenant/test/test_tenant_wise.py
eox_tenant/test_utils.py
requirements.in
requirements.txt

This allows to override the model GeneratedCertificates model, using monkey patch in order to filter the certificates by org.

Make certificates tenant aware.

---

eox_tenant/tenant_wise/__init__.py

This has been override in order to avoid performance issues, since there are a lot certificates.

Remove GeneratedCertificate override.

---

eox_tenant/tenant_wise/proxies.py

This PR adds a method so that the SiteConfigProxy also allows the platform code to access the `.values` property of the SiteConfig.
This is only used at helpers.has_configuration_override but impacts many areas of the code. Until the removal of microsites it was not a problem due to how the microsites backend handled the defaults, but now it is more standard

Add the capacity to read the values at the proxy

---

eox_tenant/settings/aws.py
eox_tenant/settings/common.py
eox_tenant/tenant_wise/__init__.py
eox_tenant/tenant_wise/context_managers.py
eox_tenant/tenant_wise/proxies.py
requirements.txt

This changes overrides the save method for GeneratedCertificate model and allows to use the TenantGeneratedCertificatedProxy in the  lms.djangoapps.certificates.queue module.

Use TenantGeneratedCertificatedProxy in queue cretificates module.

---

eox_tenant/apps.py
eox_tenant/management/commands/change_domain.py
eox_tenant/management/commands/edit_tenant_values.py
eox_tenant/models.py
eox_tenant/settings/test.py
eox_tenant/tenant_wise/proxies.py
eox_tenant/test/test_async_utils.py
eox_tenant/test/test_change_domain.py
eox_tenant/test/test_edit_tenant_values.py
eox_tenant/test/test_receivers_helpers.py
eox_tenant/test/test_signals.py
eox_tenant/test/test_tenant_wise.py
eox_tenant/test/test_views.py
eox_tenant/urls.py
eox_tenant/views.py

This PR fixes:
**1.** The following errors for test-3.6 in circle CI:
I fixed them adding  _testservers_ to the allowed hosts doing the following:
with self.settings(ALLOWED_HOSTS=['testserver']):
response = self.client.get(reverse('eox-info'), HTTP_HOST='testserver')
In the following file: eox_tenant/test/test_views.py
I'm not sure why this happened using python 3.6. If you know, please comment on this post.
**2.** After fixing 1, another error came up in the same file:
eox_tenant/test/test_views.py", line 34, in test_view_info_response_data
version = version.replace('\n', '')[1:]
TypeError: a bytes-like object is required, not 'str'
What I did to fix it was adding the _decode_ method to the _check_output_ outputs in eox_tenant/test/test_views.py and eox_tenant/views.py. 
The main …

PR for fixed Dmo/added info view 

---

setup.cfg

This PR adds settings in setup.cfg for using _isort_ in the project, this allows ordering the imports as follows:
1. Future imports
2. Python Standard Libraries
3. Django core
4. Third-party libraries (related or not to Django)
5. First party libraries (that is, our project’s imports)
6. Local imports
I used this configuration to sort all eox_tenant files, then I ran make run-quality-test and got 10/10.
Also, what do you think about the settings?
See references:
[Orginize imports reference](https://simpleisbetterthancomplex.com/packages/2016/10/08/isort.html)
[Isort settings](https://github.com/timothycrosley/isort/wiki/isort-Settings)
[Section settings](https://github.com/timothycrosley/isort#custom-sections-and-ordering)
@morenol 
@andrey-canon

Added setup for isort in setup.cfg

---

eox_tenant/test/test_admin.py

This PR tests some methods in admin.py:
- Tested methods in MicrositeAdmin class: sitename, template_dir, course_org_filter, ednx_signal
- Tested methods in TenantConfigAdmin class: sitename, template_dir, course_org_filter, ednx_signal
Increases the coverage in 4% approx.
@morenol

Added tests for some methods in admin

---

setup.cfg

This PR adds a new line in the isort setup so the imports are ordered as follows:
Future imports
Python Standard Libraries
Django core
Third party libraries (related or not to Django)
First party libraries (that is, our project’s imports)
Local imports
The line added is:
`default_section = THIRDPARTY`
@morenol 
@andrey-canon

FIXED isort setup

---

eox_tenant/constants.py
eox_tenant/edxapp_wrapper/backends/certificates_module_i_v1.py
eox_tenant/tenant_wise/__init__.py

The error was the following:
```
Operations to perform:
Apply all migrations: admin, api_admin, assessment, auth, block_structure, bookmarks, catalog, ccxcon, celery_utils, completion, consent, content_type_gating, contentserver, contentstore, contenttypes, course_action_state, course_creators, course_duration_limits, course_groups, course_modes, course_overviews, courseware, crawlers, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, embargo, enterprise, entitlements, eox_core, eox_tenant, experiments, external_auth, integrated_channel, microsite_configuration, milestones, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, problem_builder, redirects, …
```

Fixed error in migrations by checking environment

---

CHANGELOG.rst
eox_tenant/tenant_wise/__init__.py

This is part of LD-9, this change will avoid to include configuration_helpers in the contentstore.utils file

[JUNIPER LD-9]Override SiteConfiguration in contenstore.utils

---

.circleci/config.yml

By mistake the pypi section was removed in this pr https://github.com/eduNEXT/eox-tenant/pull/106/files, this reverts these changes.

Add pypi to circleci

---

eox_tenant/tenant_wise/proxies.py

This PR adds site_values as property to SiteConfiguration proxy, this is done due to this change: https://github.com/edx/edx-platform/pull/23306/files
Thank you for the help! @andrey-canon

Fix proxy compatibility issue in juniper

---

eox_tenant/widgets.py

This PR fixes the following error when entering invalid JSON values in TenantConfig admin:
Instead should be:

Fix error 500 when entering invalid JSON

---

eox_tenant/views.py

Moved git_data inside try-except block, to avoid the following error in Juniper stage:
This view is a copy from the plugin eox-hooks

Fix error 500 in eox-info view

---

eox_tenant/templatetags/ednx.py

This PR solves the branding issues in the account activation email.
When the account activation email is sent, the base template of the email calls the simple_tag microsite_get_value(), to obtain the EMAIL_LOGO_PATH value from the microsite and display it in the email.
As this email is sent by the async server, microsite_get_value() returns None, since at some point it has to call get_current_site() that does not find any request.
To solve this problem, the simple_tag tenant_get_value () (microsite_get_value () is deprecated) was modified so that it looks for the value directly in the settings when 'USE_EOX_TENANT' is True.

Fix account activation email

---

CHANGELOG.rst
eox_tenant/settings/common.py
eox_tenant/settings/test.py
eox_tenant/validators.py

The method save_beare_token generated an 500 error when the site was not allowed hence the restriction was moved to `_load_application`.

Fix token restriction.

---

CHANGELOG.rst
eox_tenant/settings/test.py

The platform tests for oauth_dispatch fail due to the override of the OAUTH2_PROVIDER['OAUTH2_VALIDATOR_CLASS'] setting
This PR changes the OAUTH2_PROVIDER plugin setting to its default to avoid the tests from the LMS from failing

fix: OAUTH2_PROVIDER test setting

---

CHANGELOG.rst
eox_tenant/signals.py
eox_tenant/test/test_signals.py
requirements/base.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/tox.txt

This PR adds support for message passing via protocol V2. Protocol 2 as opposed to protocol 1, doesn't allow sending custom headers, so we decided to send `eox_tenant_sender` inside the body's kwargs fixing the following error:
```
2021-11-17 19:42:04,799 INFO 547407 [celery.worker.strategy] [user None] [ip None] strategy.py:157 - Received task: eox_hooks.tasks.create_enrollments_for_program[3379139c-4892-4ba3-bf18-b05d1139542f]  
2021-11-17 19:42:04,803 WARNING 547931 [eox_tenant.signals] [user None] [ip None] signals.py:232 - Could not find the host information for eox_tenant.signals. 
2021-11-17 19:42:04,819 ERROR 547931 [eox_hooks.tasks] [user None] [ip None] tasks.py:58 - Couldn't create enrollment for course-v1:demo-site+DMS401+02 because the configuration is not valid: invalid …
```

feat: adding support for messages passing via protocol V2

---

eox_tenant/tenant_wise/proxies.py
eox_tenant/test/test_tenant_wise.py
eox_tenant/utils.py

Some [recent changes](https://github.com/edx/edx-platform/pull/26435) use the value of `site_values` in the email templates context, this causes errors when attempting to serialize the email message because eox-tenant returns a dictionary with all the Django Settings values. To avoid this, only return a serializable subset of the settings.
Try to send an email (one of the easiest is account verification)
- Create a new user
- Set the user as inactive
- Try to login
The email should be sent without errors and with the correct context for the tenant.
I performed a small grep of `site_values` on edunext-platform and ignoring the test files and po files it's mostly used to obtain the value of `course_org_filter` and `COURSE_CATALOG_API_URL`.
Considering our current pattern is to access the …

Return only a serializable subset of settings in `site_values`

---

CHANGELOG.rst
README.rst
eox_tenant/edxapp_wrapper/backends/edxmako_l_v1.py
eox_tenant/settings/common.py

This PR(s) updates edxmako backend so it's lilac compatible.
Go to a tenant without configuration. Before this change, it'll crash and raise [this error](https://sentry.io/organizations/edunext/issues/2911742594/?project=6134348&query=&statsPeriod=14d).
[Sys path removal](https://github.com/openedx/edx-platform/blob/master/docs/decisions/0007-sys-path-modification-removal.rst)

fix: add lilac backend for edxmako

---

eox_tenant/middleware.py
eox_tenant/test/test_middleware.py

the method [get_value](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/site_configuration/helpers.py#L119) tries to perform a dictionary update using the found value, this should fail if the value is not a dictionary however when the course_org_filter is a list with an org of two letters, this doesn't fail, this performs the update a return a dictionary 
```
course_org_filter = ["AB"]
configuration_helper.get_value('course_org_filter', set([]))
```
the method [get_current_site_orgs()](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/site_configuration/helpers.py#L216) perfoms the verification and return the right value
Add MicrositeCrossBrandingFilterMiddleware middleware
Create a site with course_org_filter = ["AB"]
Create a course …

fix: Use get_current_site_orgs instead of get_value

---

eox_tenant/api/v1/permissions.py
eox_tenant/api/v1/tests/test_microsites.py
eox_tenant/api/v1/tests/test_permissions.py
eox_tenant/api/v1/tests/test_routes.py
eox_tenant/api/v1/tests/test_tenant_config.py
eox_tenant/api/v1/viewsets.py
eox_tenant/apps.py
eox_tenant/edxapp_wrapper/backends/bearer_authentication_l_v1.py
eox_tenant/edxapp_wrapper/backends/bearer_authentication_test_v1.py
eox_tenant/edxapp_wrapper/bearer_authentication.py
eox_tenant/settings/common.py
eox_tenant/settings/test.py

Currently, the tenant API permission class [EoxTenantAPIPermission](https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/api/v1/permissions.py#L11) only allows superusers to make requests through a basic auth scheme.
https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/api/v1/permissions.py#L10-L13
In this PR we add a Bearer authentication scheme to the API
A new file containing the tests for the API permissions was added, and the test cases for the permissions were removed from the API tests.
This implementation was based on the eox-core API permission protocol
https://github.com/eduNEXT/eox-core/blob/master/eox_core/api/v1/permissions.py#L32
To grant access, the EoxTenantAPIPermission class now checks multiple things:
- Staff members always have access, so If the …

feat: add BearerAuthentication to API

---

eox_tenant/filters/README.rst
eox_tenant/filters/__init__.py
eox_tenant/filters/pipeline.py
eox_tenant/filters/test/test_pipeline.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/tox.txt

This PR adds a custom filter pipeline to get course enrollments from tenant site where a user makes the request.
The idea is including some changes in _openedx-filters_ and _edx-platform_ repositories to anyone implement the filter function, and one clear example to use is this custom pipeline on eox-tenant plugin.
**Dependencies for now**:
- https://github.com/eduNEXT/edunext-platform/pull/696
**Future dependencies**:
- openedx/openedx-filters
- openedx/edx-platfom
1. Create an environment, you can use strain.yml bellow.
```yml
STRAIN_NAME: nuez
STRAIN_TUTOR_VERSION: v14.1.0
DOCKER_IMAGE_OPENEDX_DEV: docker.io/ednxops/distro-edunext-edxapp-dev:nuez
DOCKER_IMAGE_OPENEDX: docker.io/ednxops/distro-edunext-edxapp:nuez
EDX_PLATFORM_REPOSITORY: https://github.com/eduNEXT/edunext-platform.git …
```

(FFI-3/DS-300) filter user's course enrollment by microsite request

---

.github/workflows/bump_version.yml

This PR updates the version of the changelog updater. This correct the error creating the version in eox-tenant.
I replicated the error in a fork and changed the version, and it works. 
In my fork: in the docs commit, I have the same error in eduNEXT; and the next commit fixed it.
Fork: https://github.com/MaferMazu/eox-tenant/commits/master

ci: update the changelog updater step in bumpversion DS-305

---

eox_tenant/middleware.py

This adds the route domain if the tenant has tenant route a associated. This also avoids the creation of a site record with the same domain as a route created.
By the moment the objective branch is `open-release/mango.master` https://github.com/eduNEXT/eox-tenant/tree/open-release/mango.master a branch that I created from the v6.2.0 release. Because is the version eox-tenant in nelp is being used: https://github.com/eduNEXT/ednx-strains/blob/open-release/nelp/nelp/mango/strain.yml#L174
Useful information to include:
- This is very helpful for views that use `site.domain`. 
In nelp there was a case when rendering the program's view was failing due to the build of the domain didn't exist or being wrong.
https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/learner_dashboard/prog …

feat: add route domain to proxy also the `domain`

---

.github/workflows/tests.yml

Run tests with open-release/* branches, this is required since NELP has a custom branch called [open-release/mango.nelp](https://github.com/eduNEXT/eox-tenant/tree/open-release/mango.nelp)
Make a PR against open-release/mango.nelp, all tests should run.

ci: add open-release/* branches to github workflows

---

eox_tenant/admin.py

This PR adds an extra check before registering eox-tenant models into the Django Admin page. We aim to only register those models in the LMS service.
1. Install this version of the plugin in your development environment. In the LMS/CMS
2. Then restart services
3. Check both admins, the multitenancy models should be registered just in the LMS.
This PR solves: https://github.com/eduNEXT/eox-tenant/issues/154 by removing any modifications from the studio admin page. I tested this in olive & nutmeg.

refactor!(DS-434): avoid registering models in services different than LMS

---

eox_tenant/api/v1/permissions.py

This MR fixes tutor build failure due to permissions file being loaded before migrations. The fix is inspired by https://github.com/eduNEXT/eox-tenant/pull/145
Install this plugin in tutor and run `tutor images build openedx`, it will fail with database `ImproperlyConfigured` error. Update your local copy of plugin with this change and run build, it should work.

fix: bypass load permission if migrations not completed

---

eox_tenant/edxapp_wrapper/backends/dark_lang_middleware_o_test_v1.py
eox_tenant/edxapp_wrapper/backends/dark_lang_middleware_o_v1.py
eox_tenant/edxapp_wrapper/dark_lang_middleware.py
eox_tenant/settings/common.py
eox_tenant/settings/test.py
eox_tenant/tenant_aware_functions/released_languages.py
eox_tenant/tenant_wise/__init__.py
eox_tenant/tenant_wise/proxies.py

This PR extract LC-V2 from the platform to eox-tenant.
LC-V2 allows you to have released_languages site aware in: `openedx/core/djangoapps/lang_pref/api.py`, `openedx/core/djangoapps/dark_lang/middleware.py`. And set a default value to HTTP_ACCEPT_LANGUAGE.
More context: [LC-V2 Doc](https://docs.google.com/document/d/1EO5aDX8CrsDRwdlqtu-VE5SduQmQ3xYLpShfOdhXYqQ/edit?usp=sharing)
- You need to have a Tutor environment with eox-tenant installed with this version.
- You need to add some settings for eox-tenant and the selectors to work (you can add it in env/apps/openedx/config/lms.env.yml and in env/apps/openedx/config/cms.env.yml):
- USE_EOX_TENANT: true
- Y en FEATURES:
- EDNX_SITE_AWARE_LOCALE: true
- SHOW_FOOTER_LANGUAGE_SELECTOR: true
- SHOW_HEADER_LANGUAGE_SELECTOR: true
- Create a …

feat: having released_languages tenant and site aware DS-553

---

.github/workflows/labeler.yml
eox_tenant/filters/pipeline.py
eox_tenant/filters/test/test_pipeline.py
requirements/base.txt
requirements/test.txt

This PR make a refactor to use FFI-3 with [openedx-filters](https://github.com/openedx/openedx-filters/blob/main/openedx_filters/learning/filters.py#L523)
Refactor from https://github.com/eduNEXT/eox-tenant/pull/156
1. Create two Tenant sites and add at less one course on each one. Go on to create sites: http://{lms.base}:8000/admin/eox_tenant/tenantconfig/
2. In a course, in Studio, set ``Mobile Course Available`` true. Go on to configure the key: http://{studio.base}:8001/settings/advanced/{your_course_id}
3. Enroll a user (user don't have to be a staff user) in a course on different sites.
4. Add the following configurations to your configuration site.
```json
"OPEN_EDX_FILTERS_CONFIG": {
"org.openedx.learning.course_enrollment_queryset.requested.v1": {
"fail_silently": false, …
```

refactor: use CourseEnrollmentQuerysetRequested from openedx-filters

---

commitlint.config.js

This adds openedx commit lintern rules.
This is inspired by the following PR:
https://github.com/eduNEXT/shipyard-infrastructure/pull/25/files
This fixes the footer long chars error.
This is mostly based on: 
https://github.com/openedx/edx-lint/blob/master/commitlint.config.js
In particular, limiting the length of a line in the commit body might be detrimental when including external links.

feat: add openedx commitlint.config.js

---

eox_tenant/models.py
eox_tenant/tenant_wise/proxies.py

This PR is created for **a necessity arisen in the [PR #808 from edunext-platform](https://github.com/eduNEXT/edunext-platform/pull/808)** and allows using boolean types as values because when some tenant properties have a value `False` or `True`, this is used to run two conditionals. e.g. if a tenant setting `ENABLE_COURSE_AUTHORING_MFE` has a value `False`, even though we want to send the value `False`, the conditional is skipped and is returned a None instead of `False` 
At this moment the useful way to test this PR would be running the [PR #808 from edunext-platform](https://github.com/eduNEXT/edunext-platform/pull/808)

fix: allow using boolean as values in tenant configs when getting settings by organization

---

eox_tenant/middleware.py

This add the route domain if the tenant has tenant route a associated. This also avoid the creation of a site record with the same domain of a route created.
Migration pr of  https://github.com/eduNEXT/eox-tenant/pull/162

feat: add route domain to proxy the site `domain`

---

eox_tenant/models.py
eox_tenant/tenant_wise/proxies.py
eox_tenant/test/test_tenant_wise.py

If multiple tenant configs are enabled for a given org, fetching value from site config for the organization should return current site config value if the org is included in the org_filter.
`Private-ref`: [BB-7927](https://tasks.opencraft.com/browse/BB-7927)
See https://github.com/open-craft/eox-tenant/pull/3

fix: prioritize current site setting for org value

---

eox_tenant/edxapp_wrapper/backends/edx_auth_n_v1.py
eox_tenant/settings/common.py
eox_tenant/settings/production.py

**Summary:**
This PR fixes a bug in the `eox-tenant` functionality that restricted users from entering the LMS by their sign up source. The bug was introduced during the migration to Nuez, due to a change in the OpenEdX authentication backend.
**Details:**
- The migration to `Nuez` replaced `EdxRateLimitedAllowAllUsersModelBackend` with `AllowAllUsersModelBackend`, this change affected the `eox-tenant` functionality that restricted users by their sign-up source.
- For more information on the change in the authentication backend, see the Nutmeg release notes: [Nutmeg Release Notes](https://docs.openedx.org/en/latest/community/release_notes/nutmeg.html#removed-in-nutmeg).
**Steps to reproduce the issue:**
1. Have an environment with eox-tenant properly configured.
2. Create two tenants: A …

Correcting user restriction behavior by sign up source in eox-tenant

---

eox_tenant/apps.py
eox_tenant/constants.py
eox_tenant/models.py
eox_tenant/receivers_helpers.py
eox_tenant/signals.py
eox_tenant/test/test_receivers_helpers.py
eox_tenant/test/test_signals.py

Makes use of `studio_configs` field from `TenantConfig` table to keep studio configuration separate from LMS configs. It achieves the separation by having separate signal handlers for LMS and studio.
**This is required** due to conflicts between lms and studio settings. For example, repopulating `third_party_auth` plugin overrides few settings, one of which is `SOCIAL_AUTH_STRATEGY`. It needs to be set to `auth_backends.strategies.EdxDjangoStrategy` for studio and `common.djangoapps.third_party_auth.strategy.ConfigurationModelStrategy` for lms for third_party auth to work smoothly.
* Setup nutmeg or master devstack.
* Install this plugin in both studio and lms.
* Add a new tenant, for example, lacolhost.com (points to localhost), so you can visit lacolhost.com:18000 to access LMS and …

feat: separate studio config and handler

---

eox_tenant/settings/test.py
eox_tenant/test/tutor/tutor/conftest.py
eox_tenant/test/tutor/tutor/integration_test_tutor.py
eox_tenant/test/tutor/tutor/pytest.ini
requirements/test.in
requirements/test.txt

This PR add integration test file
- In a Quince or Palm environment install eox-tenant, I used docker-compose.override.yml
- Go to bash:
`tutor dev run lms bash`
`make test-requirements`
`pytest -s --ds=lms.envs.tutor.test /openedx/eox-tenant/eox_tenant/test/tutor`
https://edunext.atlassian.net/browse/DS-906

feat: add integration test

---

eox_tenant/settings/common.py
eox_tenant/utils.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/pip-tools.txt
requirements/test.txt

This PR adds the creation (if it does not exist) of an edX organization each time the `course_org_filter` property is updated in the **LMS Configs** of each **Tenant Config**.
1. Install the plugin with these changes (If you are installing it for the first time you should run the migrations).
2. Create a new **Tenant Config** from `{lms-domain}/admin/eox_tenant/tenantconfig/`
3. In the **lms config** field add the **course_org_filter** property and save:
```json
{
"course_org_filter": [
"edunext",
"edX",
...
]
}
```
4. Go to `{lms-domain}/admin/organizations/organization/`, you should see the new organizations.
https://github.com/eduNEXT/eox-tenant/issues/165

feat: create edx organization when updating course_org_filter `DS-961`

---

.github/workflows/bump_version.yml

This PR changes the bump version GitHub Action name to trigger the GH Actions and test that bump version is disabled

temp: disable automatic bump-version

---

eox_tenant/test/tutor/integration_test_tutor.py

This PR adds validation for the /eox-tenant/eox-info endpoint in the integration test
Checks:
- Integration / integration-test (<17.0.0) (pull_request)
- Integration / integration-test (<18.0.0) (pull_request)
SITE_ID = 2 is used to fix the error: django.contrib.sites.models.Site.DoesNotExist: Site match query does not exist.
When running an instance, SITE_ID is 2, so the setting was overridden so that during testing it also takes the SITE_ID = 2
https://edunext.atlassian.net/browse/DS-993

feat: add api integration test

---

README.rst
eox_tenant/edxapp_wrapper/backends/branding_api_l_v1.py
eox_tenant/settings/common.py
eox_tenant/settings/production.py

This PR improves the repository documentation for a better understanding of the eox-tenant plugin.
For the plugin description
>  Plugin for managing multiple tenants (organizations) within a single Open edX instance, replacing the microsites and site configuration features with a more robust multi-tenancy model.
**Proposal** 
➡️ Maintain the settings configuration for the current release. 
- **Simplification**: Find the necessary information without being distracted by details that may no longer be relevant (e.g. Ironwood).
- **Relevance**: Users typically work with recent versions of software. Documenting the latest settings ensures that our documentation is pertinent and useful for most users.
- **Maintenance**:  We lower the risk of outdated information and reduce the effort required …

docs: improve the documentation

---

.github/dependabot.yml
.github/workflows/bump_version.yml
.github/workflows/labeler.yml
.github/workflows/python-publish.yml
.github/workflows/tests.yml

This PR adds the `dependabot.yml` file to perform automated upgrading to GitHub Actions. The current configuration creates a Weekly PR (on Mondays) with the changes.
Also, the versions of the workflow actions are updated to use the MAJOR version (if possible).
[AP-1514](https://edunext.atlassian.net/browse/AP-1514)
[AP-1514]: https://edunext.atlassian.net/browse/AP-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add dependabot config for enable github action auto update `AP-1514`

---

.github/workflows/integration-test.yml
CHANGELOG.md
README.rst
eox_tenant/__init__.py
requirements/base.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/tox.txt
setup.cfg

This PR adds support for the Open edX Sumac release.
These were the changes made:
- Upgraded requirements based on the `edx-platform` Sumac release. 
- Updated the Integration Tests to use the Sumac release with Tutor.
1. Create an environment with Sumac release, you can use [Tutor](https://docs.tutor.overhang.io/index.html) or [TVM](https://github.com/eduNEXT/tvm).
2. Install the Django plugin `eox-tenant` using this PR branch, you can use the steps in [Tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Run the [test cases](https://docs.google.com/document/d/1qqsc6FJ9JTx8xx43TvJfvVpy97_BakL-0IGta4bbshg). In this file, you can find more information about the plugin configuration.
- [Jira …

perf: sumac release support `AP-1580`

---

.github/workflows/commitlint.yml

This PR updates the `commitlint.yml` workflow to use Open edX's reusable workflow. This change is mainly to align with the platform workflows.
See the **Lint Commit Messages** job
- https://github.com/eduNEXT/eox-theming/pull/72#issuecomment-2456698858
[AP-1595](https://edunext.atlassian.net/browse/AP-1595)
[AP-1595]: https://edunext.atlassian.net/browse/AP-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: use openedx commitlint workflow `AP-1595`

---

.github/workflows/integration-test.yml

Renamed the `nightly` version in the Tutor Integration Tests Workflow to `main`. This aligns with the recent Tutor branch renaming discussed [here](https://discuss.openedx.org/t/tutor-branches-rename/14455).
- Tutor has officially renamed the `nightly` branch to `main`.  
- Updated the `nightly` tutor_version in the workflow to ensure compatibility with the new branch structure.

chore(integration-tests-workflow): rename 'nightly' for 'main'

---

CHANGELOG.md
eox_tenant/__init__.py
eox_tenant/api/v1/serializers.py
eox_tenant/api/v1/tests/test_tenant_config.py
eox_tenant/api/v1/viewsets.py
setup.cfg

This PR introduces two key improvements to the `TenantConfigViewSet`:
1. **New `update-by-domain` action**: Allows updating a `TenantConfig` by searching for it using its domain `route__domain`, rather than the default lookup fields (`id` or `external_key`).
2. **Stronger JSON field validation in `TenantConfigSerializer`**: Ensures that the `lms_configs`, `studio_configs`, `theming_configs`, and `meta` fields must always be dictionaries.
In Control Center, an automated process is required to **create new subscriptions** and correctly link them to their respective Open edX sites. To achieve this, Control Center must be able to **update the `external_key` of the site (TenantConfig)** so that it matches the `external_key` assigned to the tenant in Control Center.  
This alignment is crucial …

feat: add `update-by-domain` Action and Enforce JSON Field Validations in TenantConfig API
